// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


var Unions = { };

var node = ( {
  "kind": "Fragment",
  "name": "IndexRoot_AddressEntry_vendorFollowUp",
  "type": "VendorFollowUp",
  "metadata": null,
  "argumentDefinitions": [],
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "name": "id",
      "args": null,
      "storageKey": null
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "name": "agent",
      "storageKey": null,
      "args": null,
      "concreteType": "Agent",
      "plural": false,
      "selections": [
        {
          "kind": "ScalarField",
          "alias": null,
          "name": "brandingColor",
          "args": null,
          "storageKey": null
        }
      ]
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "name": "contact",
      "storageKey": null,
      "args": null,
      "concreteType": "Contact",
      "plural": false,
      "selections": [
        {
          "kind": "ScalarField",
          "alias": null,
          "name": "firstName",
          "args": null,
          "storageKey": null
        },
        {
          "kind": "ScalarField",
          "alias": null,
          "name": "address",
          "args": null,
          "storageKey": null
        }
      ]
    }
  ]
} );

export {
  Unions ,
  node ,
  
}
/* node Not a pure module */
