// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as ReasonRelay from "reason-relay/src/ReasonRelay.bs.js";

var Unions = { };

var Types = { };

var fragmentConverter = ( {} );

function convertFragment(v) {
  return ReasonRelay._convertObj(v, fragmentConverter, /* () */0, undefined);
}

var Internal = {
  fragmentConverter: fragmentConverter,
  fragmentConverterMap: /* () */0,
  convertFragment: convertFragment
};

var Utils = { };

var node = ( {
  "kind": "Fragment",
  "name": "IndexRoot_AddressEntry_vendorFollowUp",
  "type": "VendorFollowUp",
  "metadata": null,
  "argumentDefinitions": [],
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "name": "id",
      "args": null,
      "storageKey": null
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "name": "agent",
      "storageKey": null,
      "args": null,
      "concreteType": "Agent",
      "plural": false,
      "selections": [
        {
          "kind": "ScalarField",
          "alias": null,
          "name": "brandingColor",
          "args": null,
          "storageKey": null
        }
      ]
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "name": "contact",
      "storageKey": null,
      "args": null,
      "concreteType": "Contact",
      "plural": false,
      "selections": [
        {
          "kind": "ScalarField",
          "alias": null,
          "name": "firstName",
          "args": null,
          "storageKey": null
        },
        {
          "kind": "ScalarField",
          "alias": null,
          "name": "address",
          "args": null,
          "storageKey": null
        }
      ]
    }
  ]
} );

export {
  Unions ,
  Types ,
  Internal ,
  Utils ,
  node ,
  
}
/* fragmentConverter Not a pure module */
