// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


var Unions = { };

var node = ( {
  "kind": "Fragment",
  "name": "Navigation_agent",
  "type": "Agent",
  "metadata": null,
  "argumentDefinitions": [],
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "name": "id",
      "args": null,
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "name": "brandingColor",
      "args": null,
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "name": "logoUrl",
      "args": null,
      "storageKey": null
    }
  ]
} );

export {
  Unions ,
  node ,
  
}
/* node Not a pure module */
