// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as ReasonRelay from "reason-relay/src/ReasonRelay.bs.js";

var Unions = { };

var Types = { };

var FragmentConverters = { };

var fragmentConverter = ( {} );

function convertFragment(v) {
  return ReasonRelay._convertObj(v, fragmentConverter, /* () */0, undefined);
}

var Internal = {
  fragmentConverter: fragmentConverter,
  fragmentConverterMap: /* () */0,
  convertFragment: convertFragment
};

var node = ( {
  "kind": "Fragment",
  "name": "Navigation_agent",
  "type": "Agent",
  "metadata": null,
  "argumentDefinitions": [],
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "name": "id",
      "args": null,
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "name": "brandingColor",
      "args": null,
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "name": "logoUrl",
      "args": null,
      "storageKey": null
    }
  ]
} );

export {
  Unions ,
  Types ,
  FragmentConverters ,
  Internal ,
  node ,
  
}
/* fragmentConverter Not a pure module */
