// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function unwrap(wrapped) {
  switch (wrapped) {
    case "PRIVATE" :
        return /* PRIVATE */155386083;
    case "PUBLIC" :
        return /* PUBLIC */427175081;
    default:
      return /* FUTURE_ADDED_VALUE__ */-769308010;
  }
}

function wrap(t) {
  if (t !== 155386083) {
    if (t >= 427175081) {
      return "PUBLIC";
    } else {
      return "";
    }
  } else {
    return "PRIVATE";
  }
}

var Enum_CacheControlScope = {
  unwrap: unwrap,
  wrap: wrap
};

export {
  Enum_CacheControlScope ,
  
}
/* No side effect */
