// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function EmptyContent(Props) {
  var emptyText = Props.emptyText;
  return React.createElement("div", {
              className: "flex h-screen"
            }, React.createElement("div", {
                  className: "m-auto flex flex-col items-center"
                }, React.createElement("img", {
                      className: "object-cover h-64 w-48",
                      src: "/homer.png"
                    }), React.createElement("div", {
                      className: "font-semibold text-yellow-800"
                    }, emptyText)));
}

var make = EmptyContent;

var $$default = EmptyContent;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
