// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function Layout(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: "antialiased text-gray-900"
            }, children);
}

var make = Layout;

var $$default = Layout;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
