// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Cn from "re-classnames/src/Cn.bs.js";
import * as React from "react";

function SVG(Props) {
  var className = Props.className;
  var className$1 = Cn.make(/* :: */[
        "fill-current",
        /* :: */[
          Cn.unpack(className),
          /* [] */0
        ]
      ]);
  return React.createElement("svg", {
              className: className$1,
              viewBox: "0 0 20 20"
            }, React.createElement("path", {
                  d: "M5 10.828l1.61-1.685 1.887 1.736L13.683 6 15 7.704l-6.548 6.074z"
                }));
}

var make = SVG;

var $$default = SVG;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
