// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Next from "nextdotbs/src/Next.bs.js";
import * as Js_dict from "bs-platform/lib/es6/js_dict.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

function getInitialProps(component) {
  return Caml_option.nullable_to_opt(component.getInitialProps);
}

function getBaseUrl(req) {
  return Belt_Option.map(req, (function (req) {
                var headers = req.headers;
                var protocol = Belt_Option.getWithDefault(Js_dict.get(headers, "x-forwarded-proto"), "http");
                var host = Belt_Option.getWithDefault(Js_dict.get(headers, "x-forwarded-host"), headers["host"]);
                return protocol + ("://" + host);
              }));
}

var Head = Next.Head;

var Link = Next.Link;

export {
  Head ,
  Link ,
  getInitialProps ,
  getBaseUrl ,
  
}
/* No side effect */
